services:
  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      - db 
    env_file:
      - .env 
    environment: 
      DB_NAME: librachat
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432   # Porta do PostgreSQL
    networks:
      - my_django_network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: librachat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_django_network 

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DB: librachat
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - my_django_network

volumes:
  db_data:

networks:
  my_django_network:
    driver: bridge
